### ISSUE TITLE
OpenRewrite fails to parse java files when using Java 23

### ISSUE THREAD

**Issue by talios** [openrewrite/rewrite#4513]
When setting `<release>23</release>` on my Maven project, OpenRewrite fails to parse Javadoc, most likely due to the updates to support Markdown Javadoc.

## What version of OpenRewrite are you using?

I am using the following versions:

```
locked org.openrewrite.maven:rewrite-maven-plugin:5.40.2;
locked org.openrewrite.recipe:rewrite-cucumber-jvm:1.5.7;
locked org.openrewrite.recipe:rewrite-java-dependencies:1.18.1;
locked org.openrewrite.recipe:rewrite-java-security:2.12.0;
locked org.openrewrite.recipe:rewrite-logging-frameworks:2.13.0;
locked org.openrewrite.recipe:rewrite-migrate-java:2.25.1;
locked org.openrewrite.recipe:rewrite-static-analysis:1.16.0;
locked org.openrewrite.recipe:rewrite-testing-frameworks:2.18.0;
locked org.openrewrite:rewrite-java:7.40.8;
```

## How are you running OpenRewrite?

```
mvn clean install org.openrewrite.maven:rewrite-maven-plugin:runNoFork
```

## What did you see instead?

```
[WARNING] There were problems parsing Foo.java
[WARNING] java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.DCTree$DCDocComment com.sun.tools.javac.tree.DocCommentTable.getCommentTree(com.sun.tools.javac.tree.JCTree)'
  org.openrewrite.java.isolated.ReloadableJava21ParserVisitor.convert(ReloadableJava21ParserVisitor.java:1666)
  org.openrewrite.java.isolated.ReloadableJava21ParserVisitor.visitCompilationUnit(ReloadableJava21ParserVisitor.java:537)
  org.openrewrite.java.isolated.ReloadableJava21ParserVisitor.visitCompilationUnit(ReloadableJava21ParserVisitor.java:73)
  com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:625)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
```

**Comment by timtebeek** [comment]
Thanks for the report @talios ! Good to track this here. I'd already explored this briefly after getting a report through
- https://github.com/PicnicSupermarket/error-prone-support/pull/1329

In short we're having to depend on an internal API, which seems to have changed.
https://github.com/openrewrite/rewrite/blob/a98d83d698dda9971c93a0767b7f85d5866f306d/rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java#L1662-L1666

```
Java 21: DCDocComment getCommentTree(JCTree tree)
Java 23: DocCommentTree getCommentTree(JCTree tree);
```

**Comment by timtebeek** [comment]
Here's a PR that aims to fix this:
- https://github.com/openrewrite/rewrite/pull/4516

**Comment by triceo** [comment]
FYI @timtebeek The issue doesn't go away after upgrading to 8.36.0.

**Comment by timtebeek** [comment]
Are you seeing the exact same error? Since that line was changed..

**Comment by triceo** [comment]
Hmm, no, I'm seeing a different one, sorry:

    Caused by: org.openrewrite.java.JavaParsingException: Failed to convert for the following cursor stack:--- BEGIN PATH ---
	at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1669)


I'll file a new issue for that.
